lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: Luis Kuhn Cuellar, Carolin Schwitalla, Sabrina Krakau
  description: Pipeline for FAIR training of bioimage deep learning models
  force: false
  is_nfcore: true
  name: nidavellir
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0dev
